language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script:  python datadrivendota/manage.py test accounts guilds heroes items leagues matches players teams utils --settings=datadrivendota.settings.test
env:
  - VALVE_RATE=.5/s BROKER_CONNECTION_TIMEOUT=6 CELERYD_CONCURRENCY=2 CELERY_IGNORE_RESULT=False CELERYD_TASK_SOFT_TIME_LIMIT=90 CELERY_REDIS_MAX_CONNECTIONS=40 CELERYD_TASK_TIME_LIMIT=60 RESULT_EXPIRY_RATE=600 RABBITMQ_USER=wattrabbit RABBITMQ_VHOST=testvhost CLOUDAMQP_URL='' REDISTOGO_URL='' MAILGUN_SMTP_LOGIN='' MAILGUN_SMTP_SERVER='' MAILGUN_SMTP_PASSWORD='' RABBITMQ_PASS='' SECRET_KEY='mustnotbeempty' DJANGO_SETTINGS_MODULE=datadrivendota.settings.local AWS_SECRET_ACCESS_KEY='' STRIPE_PUBLIC_KEY='' STRIPE_SECRET_KEY='' DJANGO_PROJECT_DIR='' AWS_ACCESS_KEY_ID='' BROKER_POOL_LIMIT=1 VERBOSE_PROFILING=True STEAM_API_KEY='' INTERCOM_API_SECRET='' AWS_STORAGE_BUCKET_NAME='' DATABASE_URL='' MAILGUN_SMTP_PORT=''
