# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160112_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='track_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tracking',
        ),
    ]
