# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import players.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160224_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='player',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='steam_id',
            field=models.BigIntegerField(db_index=True, help_text=b'The steam id to pull for this user.  Like for players.', null=True, validators=[players.validators.validate_32bit]),
        ),
    ]
