# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160224_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
