# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import players.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='steam_id',
            field=models.BigIntegerField(help_text=b'The steam id to pull for this user.  Like for players.', null=True, validators=[players.validators.validate_32bit]),
        ),
    ]
