# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_auto_20151116_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='image_failed',
            field=models.BooleanField(default=False),
        ),
    ]
