# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_league_image_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='steam_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
