# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20160203_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='steam_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='livematch',
            unique_together=set([('league_id', 'steam_id', 'radiant_team', 'dire_team')]),
        ),
    ]
