# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_auto_20160213_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livematch',
            unique_together=set([]),
        ),
    ]
