# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0017_auto_20160218_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='dire_team',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livematch',
            name='league_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='livematch',
            name='radiant_team',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
