# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_auto_20150505_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='steam_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
