# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_image_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='steam_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
