# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_playermatchsummary_all_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchsummary',
            name='parsed_with',
            field=models.CharField(default='1.0', max_length=50),
            preserve_default=False,
        ),
    ]
