# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:44
from __future__ import unicode_literals

from django.db import migrations
import matches.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_playermatchsummary_parsed_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatlog',
            name='all_income',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='building_income',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='buyback_expense',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='courier_kill_income',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='creep_kill_income',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='creep_xp',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='death_expense',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='deaths',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='earned_income',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='healing',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='hero_dmg_dealt',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='hero_dmg_taken',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='hero_kill_income',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='hero_xp',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='item_buys',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='key_bldg_dmg_dealt',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='key_bldg_kills',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='kills',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='last_hits',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='other_dmg_dealt',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='other_dmg_taken',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='roshan_kill_income',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='roshan_xp',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='combatlog',
            name='xp',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='playermatchsummary',
            name='all_data',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='agility',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='agility_total',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='armor',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='assists',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='creep_kill_gold',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='damage',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='damage_taken',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='deaths',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='denies',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='healing',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='health',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='hero_kill_gold',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='income_gold',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='intelligence',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='intelligence_total',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='items',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='kills',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='last_hits',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='lifestate',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='magic_resist_pct',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='mana',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='misses',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='nearby_creep_deaths',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='position',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='recent_damage',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='reliable_gold',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='respawn_time',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='roshan_kills',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='shared_gold',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='strength',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='strength_total',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='total_earned_gold',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='tower_kills',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='unreliable_gold',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='xp',
            field=matches.model_fields.ReplayFragmentField(blank=True, max_length=250, null=True, upload_to=b'playermatchsummaries/replays/'),
        ),
    ]
