# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20160107_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatlog',
            name='playermatchsummary',
        ),
        migrations.RemoveField(
            model_name='statelog',
            name='playermatchsummary',
        ),
        migrations.DeleteModel(
            name='CombatLog',
        ),
        migrations.DeleteModel(
            name='StateLog',
        ),
    ]
