# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_auto_20160112_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchsummary',
            name='parsed_with',
        ),
        migrations.AddField(
            model_name='match',
            name='parsed_with',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
