# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_auto_20160112_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchsummary',
            unique_together=set([('match', 'player_slot')]),
        ),
    ]
