# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_auto_20160206_1540'),
        ('matches', '0013_auto_20160205_1747'),
    ]

    operations = [
    ]
