# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_merge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalunit',
            unique_together=set([('player_match_summary', 'unit_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='pickban',
            unique_together=set([('match', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='skillbuild',
            unique_together=set([('player_match_summary', 'level')]),
        ),
    ]
