# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_auto_20160213_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchsummary',
            name='gold',
            field=models.IntegerField(null=True),
        ),
    ]
