# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_auto_20160213_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchsummary',
            name='gold_spent',
            field=models.IntegerField(null=True),
        ),
    ]
