# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_auto_20160510_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchsummary',
            name='cluster',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playermatchsummary',
            name='replay_salt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
