# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_auto_20160604_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_seq_num',
            field=models.IntegerField(blank=True, help_text=b"ID valve's play sequence", null=True),
        ),
    ]
