# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_auto_20160712_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchsummary',
            name='tower_damage',
            field=models.IntegerField(null=True),
        ),
    ]
