# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def add_replay_urls(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ReplayUrlBackend = apps.get_model("replay_url_broker", "ReplayUrlBackend")
    ReplayUrlBackend.objects.create(
        url=settings.REPLAY_SERVICE_URL,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('replay_url_broker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_replay_urls)
    ]
