# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_url_broker', '0002_auto_20160422_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='replayurlbackend',
            name='do_not_use_before',
            field=models.DateTimeField(null=True),
        ),
    ]
