# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replay_url_broker', '0003_replayurlbackend_do_not_use_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replayurlbackend',
            name='last_bad_time',
        ),
    ]
