# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('replay_url_broker', '0004_remove_replayurlbackend_last_bad_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replayurlbackend',
            name='do_not_use_before',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
