# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Submitted'), (6, 'Finding Match'), (5, 'Match Not Found'), (7, 'Match Found'), (1, 'Replay Available'), (2, 'Replay Not Available'), (3, 'Parsed'), (4, 'Complete')], default=0)),
                ('match_id', models.PositiveIntegerField(unique=True)),
                ('valve_replay_url', models.URLField(blank=True, null=True)),
                ('raw_parse_url', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
