# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 05:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserpipe', '0002_auto_20160217_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
