# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserpipe', '0003_auto_20160224_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='retries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
