# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserpipe', '0004_matchrequest_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Submitted'), (6, 'Finding Match'), (5, 'Match Not Found'), (7, 'Match Found'), (1, 'Replay Available'), (2, 'Replay Not Available'), (3, 'First-Pass Parsed'), (4, 'Complete')], default=0),
        ),
    ]
