# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserpipe', '0005_auto_20160604_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Submitted'), (6, 'Finding Match'), (5, 'Match Not Found'), (7, 'Match Found'), (1, 'Replay Available'), (2, 'Replay Not Available'), (3, 'First-Pass Parsed'), (4, 'Complete'), (8, 'Unknown error!')], default=0),
        ),
    ]
